### ISSUE TITLE
load trace failed: bad section, expected info

### ISSUE THREAD

**Issue by pspacek** [aaptel/qtwirediff#1]
First of all thanks for promisingly-looking tool!

I've attempted to use it on two attached PCAPs and the tool fails to load any of them. The error message is:
```
bad section, expected info
load trace failed
```

PCAPs:
[example.zip](https://github.com/aaptel/qtwirediff/files/5042346/example.zip)

**Comment by pspacek** [comment]
I should mention that wireshark-qt 3.2.5-1 opens both files fine.

**Comment by aaptel** [comment]
Hi Petr,

I will take a look, thanks for the report

**Comment by aaptel** [comment]
I can diff your example traces fine. Do you have the tshark binary installed in your PATH?

![image](https://user-images.githubusercontent.com/1716247/89735104-5bcb7f00-da60-11ea-9f12-ab15543f1103.png)

**Comment by pspacek** [comment]
Seems fine me:
```
$ tshark --version
TShark (Wireshark) 3.2.5 (Git commit ed20ddea8138)

Copyright 1998-2020 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <https://www.gnu.org/licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, with POSIX capabilities (Linux), with libnl 3,
with GLib 2.64.4, with zlib 1.2.11, without SMI, with c-ares 1.16.1, with Lua
5.2.4, with GnuTLS 3.6.14 and PKCS #11 support, with Gcrypt 1.8.6, with MIT
Kerberos, with MaxMind DB resolver, with nghttp2 1.41.0, with brotli, with LZ4,
with Zstandard, with Snappy, with libxml2 2.9.10.

Running on Linux 5.7.12-arch1-1, with Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
(with SSE4.2), with 15903 MB of physical memory, with locale
LC_CTYPE=en_US.UTF-8, LC_NUMERIC=en_US.UTF-8, LC_TIME=cs_CZ.UTF-8,
LC_COLLATE=en_US.UTF-8, LC_MONETARY=cs_CZ.UTF-8, LC_MESSAGES=en_US.UTF-8,
LC_PAPER=cs_CZ.UTF-8, LC_NAME=cs_CZ.UTF-8, LC_ADDRESS=cs_CZ.UTF-8,
LC_TELEPHONE=cs_CZ.UTF-8, LC_MEASUREMENT=cs_CZ.UTF-8,
LC_IDENTIFICATION=en_US.UTF-8, with libpcap version 1.9.1 (with TPACKET_V3),
with GnuTLS 3.6.14, with Gcrypt 1.8.6, with brotli 1.0.7, with zlib 1.2.11,
binary plugins supported (0 loaded).

Built using gcc 10.1.0.
```

**Comment by aaptel** [comment]
Can you uncomment the debug print in trace.cpp:27 , compile and try again?

**Comment by pspacek** [comment]
Mystery solved: This is caused by non-default configuration of columns in Wireshark. I had to run it as `WIRESHARK_CONFIG_DIR=/tmp ./qtwirediff` to make sure `tshark` does not read my personal config.

**Comment by aaptel** [comment]
ah, I guess we should somehow prevent overriding columns confs when running tshark

**Comment by enceladus3** [comment]
Still getting this error:
`WIRESHARK_CONFIG_DIR=/tmp ./qtwirediff
Gtk-Message: 11:59:52.896: GtkDialog mapped without a transient parent. This is discouraged.
bad section, expected destination
load trace failed`

It used to work just fine before rebooting the system

**Comment by enceladus3** [comment]
Probably related to:
`
    futureTrace = QtConcurrent::run([=]() {
        Trace* trace = new Trace();
        if (trace->loadTrace(fn, filter) < 0) {
	    qDebug("load trace failed");
	}
        return trace;
    });
    watcherTrace->setFuture(futureTrace);
`
from:
- https://github.com/aaptel/qtwirediff/blob/42738b055ff61a15e13a59d97cfc931ac5afbbbd/traceview.cpp

**Comment by enceladus3** [comment]
> Mystery solved: This is caused by non-default configuration of columns in Wireshark. I had to run it as `WIRESHARK_CONFIG_DIR=/tmp ./qtwirediff` to make sure `tshark` does not read my personal config.

@pspacek how did you figure out?

**Comment by pspacek** [comment]
IIRC I just uncommented https://github.com/aaptel/qtwirediff/blob/42738b055ff61a15e13a59d97cfc931ac5afbbbd/trace.cpp#L27 to see what tshark returned.

**Comment by pspacek** [comment]
> ah, I guess we should somehow prevent overriding columns confs when running tshark

Probably the safest bet would be to explicitly specify `-e`, `-E` and other related options while calling `tshark`... But I do not have time for at the moment.

**Comment by aaptel** [comment]
fixed
